### ISSUE TITLE
Documentar archivo de recocido simulado.

### ISSUE THREAD

**Issue by gonzafernan** [GinoAvanzini/IA2_2019#1]
No sé si les va a gustar.

Objetivos de cómo he documentado el A* y ahora el temple simulado:

1) La documentación creo que nos serviría mucho a la hora de hacer un coloquio del algoritmo, por eso me parece que estaría bueno que todas las cosas teóricas y el porqué de las decisiones que tomamos quede en el código.

2) Van a ver que en ambos algoritmos agrego parámetros al pedo a la función principal: son las funciones propias de como modelamos el problema. Esto es lo que me gustaría que me den el ok. Una vez que terminamos el ejercicio no cambia nada, y la idea es que si en un futuro llegamos a reutilizar esos algoritmos solo hay que redefinir esas funciones parámetro e importar el módulo del algoritmo. 

Me gustaría que me digan si les parece bien.

**Comment by adrianpajarito8** [comment]
¿La documentación hay que entregarla como parte del trabajo práctico o es solo para nosotros para cuando tengamos que explicar el código y/o estudiarlo para los parciales?
¿Esta documentación la hacemos en un archivo de texto o comentado sobre el script?
Estaría bien hacer el punto 2 después de terminar el tp. Pero si nos vendría bien documentar

**Comment by gonzafernan** [comment]
No, con documentación me refiero a los comentarios en el código, que ya los hice. El informe de todas formas es cierto hay que hacerlo y falta.

En la pestaña [project](https://github.com/GinoAvanzini/IA2_2019/projects/1) está todo lo que falta hacer.
