### ISSUE TITLE
Testeo del algoritmo genético

### ISSUE THREAD

**Issue by gonzafernan** [GinoAvanzini/IA2_2019#2]
Con @GinoAvanzini el viernes pudimos terminar, algo apurados, el algoritmo genético. Trate de documentarlo de forma que lo puedan agarrar, pero le dimos tantas vueltas que no quedó muy prolijo que digamos. La idea de este issue es que consultemos dudas y verifiquemos si esta bien.

Imposible testearlo en una solo máquina, el tiempo de ejecución es grande. Si a alguno se le ocurre alguna forma de verificar que los resultados que da son correctos genial. Lo primero que se me ocurre es una lista de pedidos intuitivos y ver si tira un layout del almacen con lógica.

[EDIT] **Propuesta para comprobar el correcto funcionamiento del algoritmo genético**

1. Inventar un determinado número de ordenes propias.
2. Ejecutar el recocido simulado repetidamente para obtener el costo para el layout default del almacen.
3. Ejecutar el algoritmo genético para dichas ordenes y obtener el supuesto layout adecuado.
4. Volver a ejecutar el temple pero esta vez para el layout optimizado, y comprobar reducciones en el costo.

**Comment by gonzafernan** [comment]
Hablando con el Franco me sugirió hacer la curva del fitness promedio de cada generación a lo largo de la ejecución.

Otra sugerencia fue hacer un gráfico de cajas, esto era más enroscado, por ahpi solo para ver.

**Comment by adrianpajarito8** [comment]
Un box and whiskers?

**Comment by gonzafernan** [comment]
Claro, igual eso sería muy si nos sobra tiempo jajaja como para ver si se puede ver algo 👌

**Comment by FrancoPalau** [comment]
[array([18,  7, 32, 24, 30, 12, 16]), array([14,  9,  5, 32,  9]), array([29, 29,  1, 15,  6, 13, 30,  9, 18]), array([16, 27,  9, 20, 30, 20, 28]), array([13,  9, 26, 20, 31, 11]), array([32, 12, 24,  1, 10, 24, 10, 16])]

Ordenes para testear con almacen de 32 elementos.

Lo del grafico de cajas esta mal, no lo hagan.

**Comment by FrancoPalau** [comment]
Pensandolo bien, el grafico de caja tiene sentido.
Cuando se utiliza un algoritmo estocastico (es decir, un algortimo que genera variables aleatorias), es buena practica correr el algoritmo multiples veces. Esto se hace para eliminar el factor "suerte" del problema:
Ejemplo: ustedes corrieron el algoritmo una vez y justo esa combinacion de valores aleatorios hizo que sus resultados sean muy buenos, pero luego al correrlo con otros valores aleatorios distintos, resulta que los resultados obtenidos fueron malos. 
Para asegurarse entonces que su algortimo funciona bien para cualquier combinación de valores, lo corren mulitples veces y guardan el resultado de cada ejecucion (por ejemplo el fitness del mejor individuo encontrado). Con esos datos, pueden hacer un grafico de caja y analizar la variacion obtenida.
Pero todo esto es muy especifico, para mostrar los resultados de un genetico lo que se hace es una curva Fitness vs iteraciones, si el fitness disminuye, el algo anda bien

**Comment by gonzafernan** [comment]
@adrianpajarito8 volviste a abrir este issue por algo en particular?

**Comment by adrianpajarito8** [comment]
Ya estaba en In Progress. Solo que apreté algo y lo metí en Done. Así que
lo volví a donde estaba y ahi les debe haber llegado el mail. No cambié
nada.

**Comment by gonzafernan** [comment]
Ah joya porque en realidad todavía no lo terminamos de testear

**Comment by gonzafernan** [comment]
Si el testeo en la [jupyter notebook](https://github.com/GinoAvanzini/IA2_2019/blob/master/TP_1/genetic-test.ipynb) creen que está bien, creo que ya podemos cerrar este issue.
