### ISSUE TITLE
Redactar informe del TP1

### ISSUE THREAD

**Issue by GinoAvanzini** [GinoAvanzini/IA2_2019#3]
Realmente hace falta redactar un informe? Tenía entendido que solo teníamos que rendir el coloquio

**Comment by gonzafernan** [comment]
Lo que le escuche al Marchetta es que no iba a pedir un "mini paper" como pedía antes, pero si un documento con todos los análisis que hicimos.

Se lo podemos volver a preguntar el jueves de última.

**Comment by GinoAvanzini** [comment]
Ok, ya generé los datos para el análisis del temple simulado en cuanto al tiempo de ejecución en función del tamaño de la orden y la mejoría en la calidad de la solución en función de la temperatura inicial (lo que es lo mismo que la cantidad de iteraciones porque estamos usando un perfil lineal con un step de 1 grado). 

Están los resultados raw en el .csv y las curvas en las spreadsheet de LibreOffice. Se pueden hacer gráficos nuevos, solo los hice ahí por rapidez. Además podríamos afinar el análisis pero creo que con lo que tenemos es suficiente para ver la tendencia y dar conclusiones
